CREATE TABLE gym_user (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pesel VARCHAR2(11) UNIQUE,
    first_name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100) NOT NULL,
    email VARCHAR2(255) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    role VARCHAR2(20) NOT NULL CHECK (role IN ('CLIENT','TRAINER','RECEPTIONIST','MANAGER','ADMIN')),
    status VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','INACTIVE'))
);

CREATE TABLE club (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    address VARCHAR2(255) NOT NULL,
    opening_hours VARCHAR2(50)
);

CREATE TABLE equipment (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id NUMBER NOT NULL,
    name VARCHAR2(100) NOT NULL,
    status VARCHAR2(50) NOT NULL CHECK (status IN ('OPERATIONAL', 'MAINTENANCE', 'BROKEN')),
    last_inspection_date DATE,
    FOREIGN KEY (club_id) REFERENCES club(id)
);

CREATE TABLE promo_campaign (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    target_group VARCHAR2(100),
    budget NUMBER(10,2),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL
);

CREATE TABLE discount (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id NUMBER NOT NULL,
    discount_type VARCHAR2(20) CHECK (discount_type IN ('PERCENT','AMOUNT')),
    discount_value NUMBER(10,2) NOT NULL,
    FOREIGN KEY (campaign_id) REFERENCES promo_campaign(id)
);

CREATE TABLE pass_type (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL,
    base_price NUMBER(10,2) NOT NULL
);

CREATE TABLE campaign_pass (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id NUMBER NOT NULL,
    pass_type_id NUMBER NOT NULL,
    FOREIGN KEY (campaign_id) REFERENCES promo_campaign(id),
    FOREIGN KEY (pass_type_id) REFERENCES pass_type(id)
);

CREATE TABLE gym_pass (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    pass_type_id NUMBER NOT NULL,
    price NUMBER(10,2) NOT NULL,
    purchase_date DATE NOT NULL,
    expiration_date DATE NOT NULL,
    status VARCHAR2(20) NOT NULL CHECK (status IN ('ACTIVE','EXPIRED','SUSPENDED','FROZEN')),
    FOREIGN KEY (user_id) REFERENCES gym_user(id),
    FOREIGN KEY (pass_type_id) REFERENCES pass_type(id)
);

CREATE TABLE payment (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    gym_pass_id NUMBER, -- Za co zapłacono 
    amount NUMBER(10,2) NOT NULL,
    payment_date TIMESTAMP NOT NULL,
    method VARCHAR2(50) NOT NULL CHECK (method IN ('CASH', 'CARD', 'TRANSFER', 'BLIK')),
    status VARCHAR2(50) NOT NULL CHECK (status IN ('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED')),
    FOREIGN KEY (user_id) REFERENCES gym_user(id),
    FOREIGN KEY (gym_pass_id) REFERENCES gym_pass(id)
);

CREATE TABLE group_class (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id NUMBER NOT NULL,
    trainer_id NUMBER NOT NULL,
    name VARCHAR2(100) NOT NULL,
    schedule_time TIMESTAMP NOT NULL,
    capacity NUMBER NOT NULL,
    status VARCHAR2(50) NOT NULL CHECK (status IN ('SCHEDULED', 'CANCELED', 'COMPLETED')),
    FOREIGN KEY (club_id) REFERENCES club(id),
    FOREIGN KEY (trainer_id) REFERENCES gym_user(id)
);

CREATE TABLE reservation (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id NUMBER NOT NULL,
    class_id NUMBER,
    trainer_id NUMBER,
    reservation_date DATE NOT NULL,
    status VARCHAR2(50) NOT NULL CHECK (status IN ('CONFIRMED', 'CANCELED', 'COMPLETED')),
    FOREIGN KEY (client_id) REFERENCES gym_user(id),
    FOREIGN KEY (class_id) REFERENCES group_class(id),
    FOREIGN KEY (trainer_id) REFERENCES gym_user(id)
);

CREATE TABLE exercise_dict (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    muscle_group VARCHAR2(100),
    technique_description VARCHAR2(2000),
    required_equipment VARCHAR2(100)
);

CREATE TABLE training_plan (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trainer_id NUMBER NOT NULL,
    client_id NUMBER NOT NULL,
    name VARCHAR2(100) NOT NULL,
    created_at DATE NOT NULL,
    FOREIGN KEY (trainer_id) REFERENCES gym_user(id),
    FOREIGN KEY (client_id) REFERENCES gym_user(id)
);

CREATE TABLE plan_item (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id NUMBER NOT NULL,
    exercise_id NUMBER NOT NULL,
    sets NUMBER NOT NULL,
    reps NUMBER NOT NULL,
    weight NUMBER(10,2),
    rest_seconds NUMBER,
    FOREIGN KEY (plan_id) REFERENCES training_plan(id),
    FOREIGN KEY (exercise_id) REFERENCES exercise_dict(id)
);

CREATE TABLE message (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id NUMBER NOT NULL,
    receiver_id NUMBER NOT NULL,
    content VARCHAR2(4000 CHAR) NOT NULL,
    sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (sender_id) REFERENCES gym_user(id),
    FOREIGN KEY (receiver_id) REFERENCES gym_user(id)
);

CREATE TABLE complaint (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id NUMBER NOT NULL,
    description VARCHAR2(4000 CHAR) NOT NULL,
    status VARCHAR2(50) NOT NULL CHECK (status IN ('OPEN', 'IN_PROGRESS', 'RESOLVED', 'REJECTED')),
    FOREIGN KEY (author_id) REFERENCES gym_user(id)
);